"""Create a repository to hold the toolchains

This follows guidance here:
https://docs.bazel.build/versions/main/skylark/deploying.html#registering-toolchains
"
Note that in order to resolve toolchains in the analysis phase
Bazel needs to analyze all toolchain targets that are registered.
Bazel will not need to analyze all targets referenced by toolchain.toolchain attribute.
If in order to register toolchains you need to perform complex computation in the repository,
consider splitting the repository with toolchain targets
from the repository with sass_toolchain targets.
Former will be always fetched,
and the latter will only be fetched when user actually needs to build sass code.
"
The "complex computation" in our case is simply downloading large artifacts.
This guidance tells us how to avoid that: we put the toolchain targets in the alias repository
with only the toolchain attribute pointing into the platform-specific repositories.
"""

# def _download_info(urls, sha256):
#     return struct(
#         urls = urls,
#         sha25 = sha256,
#     )

# Add more platforms as needed to mirror all the binaries
# published by the upstream project.
PLATFORMS = {
    # "x86_64-apple-darwin": struct(
    #     compatible_with = [
    #         "@platforms//os:macos",
    #         "@platforms//cpu:x86_64",
    #     ],
    # ),
    # "aarch64-apple-darwin": struct(
    #     compatible_with = [
    #         "@platforms//os:macos",
    #         "@platforms//cpu:aarch64",
    #     ],
    # ),
    "x86_64-unknown-linux-gnu": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
        # download_info_by_version = {
        #     "1.58.3": _download_info(
        #         urls = [
        #             "https://github.com/sass/dart-sass/releases/download/1.58.3/dart-sass-1.58.3-linux-x64.tar.gz",
        #         ],
        #         sha256 = "",
        #     ),
        # },
    ),
    # "x86_64-pc-windows-msvc": struct(
    #     compatible_with = [
    #         "@platforms//os:windows",
    #         "@platforms//cpu:x86_64",
    #     ],
    # ),
}

def _toolchains_repo_impl(repository_ctx):
    build_content = """# Generated by rules_sass toolchains_repo.bzl
#
# These can be registered in the workspace file or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the sass_register_toolchains macro
# so you don't normally need to interact with these targets.

"""

    for [platform, meta] in PLATFORMS.items():
        #version = repository_ctx.attr.version
        # download_info = meta.download_info_by_version[version]
        # if not download_info:
        #     fail(
        #         "could not find download information for version {} on platform {}; edit rules_sass toolchains_repo.bzl to to fix",
        #         version,
        #         platform,
        #     )
        build_content += """
# Declare a toolchain Bazel will select for running the tool in an action
# on the execution platform.
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:sass_toolchain",
    toolchain_type = "@com_github_gonzojive_rules_sass//sass:toolchain_type",
)

""".format(
            #     http_archive(
            #     name = "@{user_repository_name}_{platform}_toolchain_sass_binary",
            #     sha256 = "{archive_sha256}",
            #     urls = {archive_urls},
            # )
            platform = platform,
            name = repository_ctx.attr.name,
            user_repository_name = repository_ctx.attr.user_repository_name,
            compatible_with = meta.compatible_with,
            #archive_sha256 = download_info.sha256,
            #archive_urls = json.encode(   .urls),
        )

    # Base BUILD file for this repository
    repository_ctx.file("BUILD.bazel", build_content)

toolchains_repo = repository_rule(
    _toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "user_repository_name": attr.string(doc = "what the user chose for the base name"),
        # "version": attr.string(
        #     doc = "Version of the dart binary to install.",
        #     default = "1.58.8",
        # ),
    },
)
